### ISSUE TITLE
WWA Phoenixのβ版で曖昧な記述がある

### ISSUE THREAD

**Issue by aokashi** [WWAWing/wwawing.github.io#5]
https://github.com/WWAWing/wwawing.github.io/blob/c9d770c690206fcc75bbaf6d61fa6a4bb3c0e17c/wwap/index.html#L84

の、`("data-classic-mode-enable",true);` にある `data-classic-mode-enable` は `data-wwa-classic-mode-enable` が正しいかと思いますが、WWA Phoenixでクラシックモードは入れるつもりで間違いないでしょうか。

また、もし行うのであれば `b=c.document.createElement("link");b.rel="stylesheet";b.href=rt+"/wwa.css";` にある `/wwa.css` も、 `/wwa_classic.css` に訂正していただくと助かります！

**Comment by rmn31415** [comment]
data-classic-mode-enable については、実装がそうなってた気がします。勘違いかもしれないので、あとでみます

wwa_classic.css については、当初採用予定でしたが、Phoenixで採用する場合はWing側の改修が必要だったので、今回は一旦見送っています。Wing側の改修が終わり次第、classicに戻そうと思います。

**Comment by rmn31415** [comment]
実装は間違ってませんでした。マニュアルが間違っていたようです。
訂正して公開済です。閉じます。
